language: r
r: bioc-
addons:
  apt:
    packages:
      - libv8-dev
      - libgit2-dev
      - libmagick++-dev
r_check_args: "--as-cran"
r_github_packages:
  - drighelli/SpatialExperiment
bioc_packages:
  - SingleCellExperiment
  - TENxPBMCData
after_success:
- Rscript -e 'covr::codecov()'
