language: r
r: bioc-
apt_packages:
- libgraphicsmagick1-dev
r_github_packages:
  - drighelli/SpatialExperiment
bioc_packages:
  - SingleCellExperiment
  - TENxPBMCData
after_success:
  - Rscript -e 'covr::codecov()'
