language: r
r:
  - release
bioc_required: true
addons:
  apt:
    packages:
      - libv8-dev
      - libgit2-dev
      - libmagick++-dev
r_github_packages:
  - drighelli/SpatialExperiment
bioc_packages:
  - SingleCellExperiment
  - TENxPBMCData
after_success:
- Rscript -e 'covr::codecov()'
