language: r
r: bioc-
r_github_packages:
  - drighelli/SpatialExperiment
bioc_packages:
  - SingleCellExperiment
  - TENxPBMCData
after_success:
  - Rscript -e 'covr::codecov()'
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
